# Generated by Django 3.2.9 on 2021-11-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'collectify_cars',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'collectify_colors',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('has_driver_licence', models.BooleanField(default=False)),
                ('car', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='collectify.car')),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='collectify.color')),
            ],
            options={
                'db_table': 'collectify_users',
            },
        ),
        migrations.CreateModel(
            name='CarHasColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_has_color', to='collectify.car')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_has_color', to='collectify.color')),
            ],
            options={
                'db_table': 'collectify_car_has_color',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='colors',
            field=models.ManyToManyField(through='collectify.CarHasColor', to='collectify.Color'),
        ),
    ]
